trigger:
- main

variables:
  devenvironment: 'development'
  tstenvironment: 'test'
  prodenvironment: 'production'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - script: |
        ls -la $(Build.SourcesDirectory)/enterprise_scale/construction_sets
      displayName: 'List contents of the source directory'

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.1.0'  # Specify the version you need
    - script: |
        terraform init
      displayName: 'Initialize Terraform'

    - task: terraformstaticcodeanalyzer@1
      inputs:
        tfsecversion: '0.58.6'
    - script: |
        tfsec $(Build.SourcesDirectory)
      displayName: 'Run tfsec scan'